# Generated by Django 3.2.5 on 2022-05-31 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazin', '0009_auto_20220531_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='adresacomanda',
            name='adresa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adresacomanda',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazin.client'),
        ),
        migrations.AlterField(
            model_name='adresacomanda',
            name='cod_postal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adresacomanda',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazin.comanda'),
        ),
        migrations.AlterField(
            model_name='adresacomanda',
            name='judet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adresacomanda',
            name='oras',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='utilizator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='id_tranzactie',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comandaprodus',
            name='cantitate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comandaprodus',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazin.comanda'),
        ),
        migrations.AlterField(
            model_name='comandaprodus',
            name='produs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazin.produs'),
        ),
        migrations.AlterField(
            model_name='produs',
            name='price',
            field=models.FloatField(),
        ),
    ]
