# Generated by Django 3.2.5 on 2022-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0010_auto_20220531_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
