# Generated by Django 3.2.5 on 2022-06-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0011_produs_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='active',
        ),
    ]
