# Generated by Django 3.2.5 on 2022-06-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0012_remove_produs_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comanda',
            old_name='client',
            new_name='customer',
        ),
    ]
