# Generated by Django 3.2.5 on 2022-06-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0015_client_parola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='digital',
        ),
    ]
